### ISSUE TITLE
[Request] Please add variations of all grates to all crates

### ISSUE THREAD

**Issue by GazbonicAcid** [ICannt/Material-Foundation#3]
Please add a variation of every grated crate for every grate "plate".

**Comment by trabpukcip** [comment]
Sure why not it is only 13 more textures

**Comment by GazbonicAcid** [comment]
I hope to god that you're serious and that that wasn't supposed to be sarcasm....
Was that serious or sarcasm?

**Comment by trabpukcip** [comment]
@GazbonicAcid if it was sarcasm you would know about it ;)

13 textures is honestly not a lot considering how many the mod already has.

![New Metal Crates With Grill](http://i.imgur.com/inqZ0If.png)
